"""course delete 3 column add 2 column

Revision ID: 02ec82f89d35
Revises: 3a3925a7855d
Create Date: 2026-07-30 20:15:33.047464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ec82f89d35'
down_revision: Union[str, Sequence[str], None] = '3a3925a7855d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('title', sa.String(length=50), nullable=False))
    op.add_column('courses', sa.Column('credits', sa.Integer(), nullable=True))
    op.drop_column('courses', 'lecturer_name')
    op.drop_column('courses', 'lecturer_room')
    op.drop_column('courses', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('lecturer_room', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('lecturer_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('courses', 'credits')
    op.drop_column('courses', 'title')
    # ### end Alembic commands ###
